env_file:
  - ./common.env
  - ./gitlab.env
  - /opt/secrets.env

nexus:
  build: ./nexus
  ports:
    - "18081:8081"

jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  links:
    - nexus:nexus
    - gitlab:gitlab
    - sonar:sonar
    - selhub:hub

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  
db:
  image: postgres
  net: container:sonar

selhub:
  image: selenium/hub
  ports:
    - 4444:4444

nodeff:
  image: selenium/node-firefox-debug
  ports:
    - 5900
  links:
    - selhub:hub

nodechrome:
  image: selenium/node-chrome-debug
  ports:
    - 5900
  links:
    - selhub:hub

postgresql:
  image: sameersbn/postgresql:9.4-8
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql

gitlab:
  image: sameersbn/gitlab:8.2.1-1
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data

redis:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
